name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check npm audit
        run: npm run check-audit

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test:unit && npm run test:e2e-headless

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VUE_SIMPLE_ECOMMERCE_APP }}'
          channelId: live
          projectId: vue-simple-ecommerce-app

      - name: Semantic releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
